### ISSUE TITLE
Should MatcherModule move from services to core?

### ISSUE THREAD

**Issue by cmungall** [cmungall/owlsim-v3#16]
We have KnowledgeBadeModule in owlsim.kb in core - should MatcherModuler also be in core? Presumably in owlsim.compute.matcher?

**Comment by ccondit** [comment]
This module is strictly for resolving short names to `ProfileMatcher` implementations - which I think only a REST client would want to do. Can move over to `core` if you think that non-REST clients would want this functionality.

**Comment by ccondit** [comment]
Renamed the module with https://github.com/cmungall/owlsim-v3/commit/0eddbc9faf368d868142a642563e02f4527d30ff to clarify the intent.

**Comment by cmungall** [comment]
use case I had in mind was a command line interface  where the user can specify a shortname.

Historically I've always done this with a big case/if/then/else switch which feels inelegant, but not a big deal

**Comment by ccondit** [comment]
Oh I see. Sure - I'll refactor this into `core` then.
