### ISSUE TITLE
missing files for performance tests

### ISSUE THREAD

**Issue by nlwashington** [cmungall/owlsim-v3#5]
the performance tests in org.monarchinitiative.owlsim.compute.matcher.perf generally do not pass due to missing files in this line of code:

load("/ontologies/hp.obo", "/data/omim-disease-phenotype.owl", "/data/disorders.ttl");		

can you either add these files to the resources directory, or comment as to where the files should be fetched from?

**Comment by ccondit** [comment]
Added a bamboo build to get CI up and running for owlsimv3:
https://bamboo.crbs.ucsd.edu/browse/MON-OV
